name: Release

on:
  push:
  release:
    types: [published]

jobs:
  publish-and-release:
    runs-on: ubuntu-latest
    name: Publish Document to Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: install font
        run: |
          sudo apt-get update && sudo apt install fonts-noto-cjk
      - run: npm install --production
      - run: npm run pdf
      - uses: actions/upload-artifact@v2
        with:
          name: curriculum-vitae
          path: README.pdf
        if: github.event_name != 'release' || github.event.action != 'published'
      - if: github.event_name == 'release' && github.event.action == 'published'
        name: Attach PDF to Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: 'README.pdf'